services:
  api-server:
    image: hzadocker/flow-issue-tracker:server
    container_name: api-server
    restart: unless-stopped
    ports: 
      - "8080:8080"
    env_file: .env.server


  reverse-proxy: 
    image: nginx:latest
    container_name: reverse-proxy
    restart: unless-stopped 
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server-configs/config.conf:/etc/nginx/conf.d/config.template
      - ./server-configs/ssl/certs/flow-cert.pem:/etc/ssl/certs/flow-cert.pem
      - ./server-configs/ssl/private/flow-key.pem:/etc/ssl/private/flow-key.pem
    env_file: .env.proxy
    command: /bin/sh -c "envsubst '$SERVER_NAME'< /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'" 
    
    