name: API CD Pipeline

on:
  push:
    branches: [ "aws" ]

jobs:

  build:

    runs-on: Reverse-Proxy

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
        clean: false


    - name: Check if Docker Installed
      run: |
        if [ -x "$(command -v docker)" ]; then
          echo "Docker installed"
        else
          chmod +x ./scripts/server/install-docker.sh
          ./scripts/server/install-docker.sh
        fi

    - name: Delete Old Containers 
      run: |
        sudo docker rm -f $(sudo docker ps -qa) || true
        sudo bash -c 'echo y | docker system prune' 

    - name: Compose Up Services
      env:
        COMPOSE_FNAME: docker-compose-lb.yml
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}}
        CONFIG_DIR: lb
      run: |
        touch .env.server 
        sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'
        chmod +x ./scripts/server/compose.sh
        ./scripts/server/compose.sh