name: API Deployment (proxied-servers)

on:
    # push:
    #     branches: [ "foo" ]
  workflow_run:
    workflows: ["API Integration"] #foo
    types:
      - completed

permissions:
  contents: write

jobs: 

  build:
    
    strategy:
      matrix:
        server: [ PROXIED_1 ]

    runs-on: 
      - self-hosted
      - ${{ matrix.server }}

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
        clean: false 

      
    - name: Delete Old Containers
      run: |
        sudo docker rm -f $(sudo docker ps -qa) || true
        sudo bash -c 'echo y | docker system prune' 


    - name: Compose Up Services 
      env:
        COMPOSE_FNAME: compose-server-proxied.yml
        API_DOMAIN: ${{ secrets[matrix.server] }}
        SERVER_NAME: ${{ secrets[matrix.server] }}
        EMAIL: ${{secrets.EMAIL}} 
        CONFIG_TYPE: proxied
        
      run: |
        echo "${COMPOSE_FNAME}"
        touch .env.server
        sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'
        chmod +x ./scripts/server/compose.sh
        ./scripts/server/compose.sh