name: API Deployment (root-server)

on:

  workflow_run:
    workflows: ["API Integration"] #foo
    types:
      - completed

jobs: 

  build:

    runs-on: [self-hosted, root-server-runner]

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
          ./compose-server-root.yml
        clean: false 

      
    - name: Delete Old Containers
      run: |
        sudo docker rm -f $(sudo docker ps -qa) || true
        sudo bash -c 'echo y | docker system prune' 


    - name: Compose Up Services 
      env:
        COMPOSE_FNAME: compose-server-root.yml
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}} 
        CONFIG_TYPE: root-server
      run: | 
        echo FOO
        touch .env.server
        touch .env.proxy
        sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'
        sudo -E bash -c 'echo "${{secrets.NGINX_ENV}}" > .env.proxy'
        cat .env.proxy
        chmod +x ./scripts/server/compose.sh
        ./scripts/server/compose.sh