name: API CD Pipeline

on:
  workflow_run:
    workflows: ["API CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    permissions:
      contents: write

    steps:
    
    - name: Pull Docker Image
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker pull $DOCKER_USERNAME/flow-issue-tracker:server
      
    - name: Delete Old Container
      run: sudo docker rm -f server-container || true
    
    - name: Create .env file
      run: |
        sudo touch .env 
        sudo chmod u+w .env
        sudo echo ${{secrets.DOTENV_KEY_SERVER}} > .env 
    
    - name: Verify
      run: sudo cat .env

    - name: Run Container w/ Latest Image
      run: |
        sudo docker run 
        --env-file ./.env
        -d -p 8080:8080 
        --name server-container 
        ${{secrets.DOCKER_USERNAME}}/flow-issue-tracker:server
        