name: API (Proxied Server(s)) CD

on:
    push:
        branches: [ "foo" ]
#   workflow_run:
#     workflows: ["API CI Pipeline"]
#     types:
#       - completed

jobs: 

  build:

    
    strategy:
      matrix:
        server: [ PROXIED_1 ]

    runs-on: 
      - self-hosted
      - ${{ matrix.server }}

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
        clean: false 

      
    - name: Delete Old Containers
      run: |
        sudo docker rm -f $(sudo docker ps -qa) || true
        sudo bash -c 'echo y | docker system prune' 


    - name: Compose Up Services 
      env:
        COMPOSE_FNAME: compose-server-proxied.yml
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}} 
        CONFIG_TYPE: proxied
      run: |
        touch .env.server && touch .env.proxy
        sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'
        sudo bash -c 'echo "SERVER_NAME"=${{ secrets[format('{0}', matrix.server)] }} > .proxy.server'
        chmod +x ./scripts/server/compose.sh
        ./scripts/server/compose.sh
