name: API CD Pipeline

on:
  workflow_run:
    workflows: ["API CI Pipeline"]
    types:
      - completed



jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    # - name: Pull Docker Image
    #   env:
        # DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    #   run: sudo docker pull $DOCKER_USERNAME/flow-issue-tracker:server

      
    # - name: Delete Old Containers
    #   run: |
    #     sudo docker rm -f api-server || true
    #     sudo docker rm -f reverse-proxy || true 
    #     sudo docker rm -f certbot || true


    - name: Fetch Dummy SSL Cert
      env:
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}}
        COMPOSE_FNAME: docker-compose-server.yml
      run: |
        touch .env.server 
        chmod +x init-encrypt-server.sh
        sudo init-encrypt-server.sh
      

    
    # - name: Load Server Environment Variables
    #   run: |
    #     sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'

        

    # - name: Run Containers
    #   run: docker compose -f docker-compose-server.yml up -d


    # - name: 'Cleanup Build Folder'
    #   run: |
    #     ls -la ./
    #     rm -rf ./* || true
    #     rm -rf ./.??* || true
    #     ls -la ./
  
        