name: API Deployment (proxied-servers)

on:
  workflow_run:
    workflows: ["API Integration"] 
    types:
      - completed

permissions:
  contents: write

jobs: 

  build:
    
    strategy:
      matrix:
        server: [SERVER_2, SERVER_3]

    runs-on: 
      - self-hosted
      - ${{ matrix.server }}

    steps:
    - run: |
        sudo -s
        ls
        sudo rm -rf /Issue-Tracker/server-configs/proxied
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
          ./compose-server-proxied.yml
        clean: false 

      
    - name: Delete Old Containers
      run: |
        sudo docker rm -f $(sudo docker ps -qa) || true
        sudo bash -c 'echo y | docker system prune' 


    - name: Compose Up Services 
      env:
        COMPOSE_FNAME: compose-server-proxied.yml
        API_DOMAIN: ${{ vars.API_DOMAIN }}
        EMAIL: ${{ secrets.EMAIL }} 
        CONFIG_TYPE: proxied
        
      run: |
        touch .env.server && touch .env.proxy
        sudo bash -c 'echo "${{ secrets.SERVER_ENV }}" > .env.server'
        sudo --preserve-env=API_DOMAIN bash -c 'echo "SERVER_NAME=$API_DOMAIN" > .env.proxy'
        chmod +x ./scripts/server/compose.sh
        ./scripts/server/compose.sh