name: API CD Pipeline

on:
  push:
    branches: [ "aws" ]

jobs:

  build:

    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
        clean: false


      
    - name: Delete Old Containers
      run: |
        sudo docker rm -f api-server || true
        sudo docker rm -f reverse-proxy || true 
        sudo docker rm -f certbot || true
        sudo bash -c 'echo y | docker system prune'

    - name: Obtain SSL Cert
      env:
        COMPOSE_FNAME: docker-compose-server.yml
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}}
      run: |
        touch .env.server 
        sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'
        chmod +x ./scripts/server/ssl-cert.sh
        ./scripts/server/ssl-cert.sh