name: API (Proxied Server(s)) CD

on:
    push:
        branches: [ "foo" ]
#   workflow_run:
#     workflows: ["API CI Pipeline"]
#     types:
#       - completed

jobs: 

  build:

    runs-on: [self-hosted, proxied-server]

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
        clean: false 

      
    - name: Delete Old Containers
      run: |
        sudo docker rm -f $(sudo docker ps -qa) || true
        sudo bash -c 'echo y | docker system prune' 


    - name: Compose Up Services 
      env:
        COMPOSE_FNAME: compose-server-proxied.yml
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}} 
        CONFIG_TYPE: proxied
      run: |
        mkdir -p certs
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ./certs/nginx.key -out ./certs/nginx.crt
