name: API CD Pipeline

on:
  push:
    branches: [ "aws" ]

jobs:

  build:

    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          ./scripts
          ./server-configs
          ./docker-compose-files
        clean: false


      
    - name: Delete Old Containers
      run: |
        ls
        
        echo foo
        echo foo
        echo foo
        echo foo
        ls docker-compose-files
        echo foo
        echo foo
        echo foo
        echo foo
        ls docker-compose-files/server

        sudo docker rm -f api-server || true
        sudo docker rm -f reverse-proxy || true  
        sudo docker rm -f certbot || true
        sudo bash -c 'echo y | docker system prune' 

    - name: Compose Up Services
      env:
        COMPOSE_FNAME: ./docker-compose-files/server/docker-compose-server.yml
        API_DOMAIN: ${{vars.API_DOMAIN}}
        EMAIL: ${{secrets.EMAIL}} 
        CONFIG_TYPE: root-server
      run: |
        touch .env.server 
        sudo bash -c 'echo "${{secrets.SERVER_ENV}}" > .env.server'
        chmod +x ./scripts/server/compose.sh
        ./scripts/server/compose.sh