name: Backend Integration

on:
  push:
    branches: [ "main" ]
    
jobs:
  # check if api code (~/server) has changes
  check-changes:
    runs-on: [self-hosted, SERVER_1] 
    # Set job outputs to values from filter step
    outputs:
      api-src: ${{ steps.filter.outputs.api-src }}
    steps:
    - run: sudo chown -R $USER .
    - uses: actions/checkout@v4
      with:
        sparse-checkout:
          ./server
    - uses: dorny/paths-filter@v3.0.2
      id: filter
      with:
        filters: |
          api-src:
            - 'server/**'
          

  # Install Docker if necessary
  check-docker:
    strategy:
      matrix:
        runner: [
          SERVER-1-RUNNER-2, 
          SERVER_2, 
          ]
    
    runs-on:
      - self-hosted
      - ${{ matrix.runner }}
      
    steps:
    - run: sudo chown -R $USER .
    - uses: actions/checkout@v4
      with:
        sparse-checkout:
          ./scripts/server/install-docker.sh
    - name: Install Docker
      run: |
        chmod +x ./scripts/server/install-docker.sh
        ./scripts/server/install-docker.sh

    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "$DOCKER_PASSWORD" | sudo docker login -u $DOCKER_USERNAME --password-stdin
        sudo usermod -aG docker $USER # add runner to docker permissions group
        sudo docker logout
        echo "$DOCKER_PASSWORD" | sudo docker login -u $DOCKER_USERNAME --password-stdin


  # Build and push api code image
  build-backend:
    needs: 
      - check-changes
      - check-docker

    if: ${{ needs.check-changes.outputs.api-src== 'true' }}
    runs-on: [self-hosted, root-server-runner]

    steps:
    - run: sudo chown -R $USER .
    - uses: actions/checkout@v4
      with:
        sparse-checkout:
          ./server
      
    - name: Build Image
      working-directory: ./server
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: sudo docker build -t $DOCKER_USERNAME/flow-issue-tracker:server .

    - name: Push to Dockerhub
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: sudo docker push $DOCKER_USERNAME/flow-issue-tracker:server