name: API CI Pipeline

on:
  push:
    branches: [ "server" ]
    
jobs:

  build:

    runs-on: [self-hosted, Reverse-Proxy]

    steps:
    - uses: actions/checkout@v4 
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      working-directory: ./server
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker build -t $DOCKER_USERNAME/flow-issue-tracker:server .

    - name: Push to Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker push $DOCKER_USERNAME/flow-issue-tracker:server
    