name: API Integration

on:
  push:
    branches: [ "aws" ]
    
jobs:

  check-changes:
    runs-on: [self-hosted, root-server] 

    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout:
          ./server
        clean: false
    - uses: dorny/paths-filter@v3.0.2
      id: filter
      with:
        filters: |
          backend:
            - 'server/**'

  # Login to build from private registry (& install Docker if necessary)
  login-docker:

    strategy:
      matrix:
        runner: [root-server-runner-2, proxied_1]

    runs-on:
      - self-hosted
      - ${{ matrix.runner }}
      
    steps:
    - uses: actions/checkout@v4
      with:
        sparse-checkout:
          ./scripts/server/install-docker.sh
        clean: false
    - name: Install Docker
      run: |
        chmod +x ./scripts/server/install-docker.sh
        ./scripts/server/install-docker.sh

    - name: Login to Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  # Build and push backend code image
  build-backend:
    needs: 
      - check-changes
      - login-docker

    if: ${{ needs.check-changes.outputs.backend == 'true' }}
    runs-on: [self-hosted, root-server]
    steps:
      
    - name: Build Image
      working-directory: ./server
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker build -t $DOCKER_USERNAME/flow-issue-tracker:server .

    - name: Push to Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: sudo docker push $DOCKER_USERNAME/flow-issue-tracker:server