name: Docker Image CI

on:
  push:
    branches: [ "aws" ]
  pull_request:
    branches: [ "aws" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      working-directory: ./server
      run: docker build -t flow-issue-tracker .
      
    - name: Tag image
      working-directory: ./server
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: docker tag flow-issue-tracker $DOCKER_USERNAME/flow-issue-tracker

    - name: Push to Dockerhub
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
      run: docker push $DOCKER_USERNAME/flow-issue-tracker:latest
    
